name: Build & Deploy with Version Time

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 替換版本時間
        run: |
          build_time=$(TZ='Asia/Hong_Kong' date '+%Y/%m/%d %H:%M:%S (GMT+8)')
          sed -i "s/{{BUILD_TIME}}/$build_time/g" index.html
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html
          git commit -m "Auto update build time" || echo "No changes"
      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
